version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.4.1-jessie-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          CC_TEST_REPORTER_ID: a393ffc3ed65bf77fd85420b8aa4a8d66947a3d3d9d2829b43c43081345b388d
          PGHOST: 127.0.0.1
          PGUSER: rails_blog
          RAILS_ENV: test

      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: rails_blog
          POSTGRES_DB: rails_blog_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      - run:
          name: "Setup codeclimate test reporter"
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: "Which bundler?"
          command: bundle -v

      - restore_cache:
          keys:
              - rails-blog-bundle-{{ checksum "Gemfile.lock" }}
              - rails-blog-bundle-

      - run:
          name: "Bundle install"
          command: bundle check || bundle install

      - save_cache:
          key: rails-blog-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: |
            bundle exec rake db:create db:schema:load --trace

      - run:
          name: Run rspec
          command: |
            bundle exec rspec -fd
            ./cc-test-reporter before-build
            ./cc-test-reporter after-build --exit-code $?
